version: '3.9'
volumes:
  peershare:
  meilisearch:
services:
  peershare:
    image: 'peershare/peershare'
    command:
    - '--dir'
    - '/data'
    - '--url'
    - 'http://0.0.0.0:3000'
    - '--meili-url'
    - 'http://meilisearch:7700'
    environment:
      RUST_LOG: info
    ports:
    - '3000:3000'
    volumes:
    - "peershare:/data"
    depends_on:
    - meilisearch
  meilisearch:
    image: 'getmeili/meilisearch:v1.2'
    command: 'meilisearch'
    environment:
      MEILI_ENV: development
    expose:
    - 7700
    ports:
    - '7700:7700'
    volumes:
    - "meilisearch:/meili_data"
