[package]
name = "blake-tree-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
blake-tree = { version = "0.1", path = "../core" }
blake-tree-fuse = { version = "0.1", path = "../fuse" }
blake-tree-http = { version = "0.1", path = "../http" }
caps = "0.5.5"
clap = { version = "4.3.3", features = ["derive"] }
dirs-next = "2.0.0"
env_logger = "0.10.0"
futures = "0.3.28"
log = "0.4.18"
surf = { version = "2.3.2", default-features = false, features = ["h1-client-rustls"] }
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }
url = "2.4.0"
