[package]
name = "blake-tree-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
blake-tree = { version = "0.1", path = "../core" }
blake-tree-http = { version = "0.1", path = "../http" }
clap = { version = "4.0.32", features = ["derive"] }
femme = "2.2.1"
tide = "0.16.0"
tokio = { version = "1.24.1", features = ["macros", "rt-multi-thread"] }
