[package]
name = "blake-tree"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
base64 = "0.21.2"
blake3 = "1.4.0"
getrandom = "0.2.10"
hex = "0.4.3"
serde = { version = "1.0.164", features = ["derive"] }
sled = "0.34.7"

[dev-dependencies]
bao = "0.12.1"
env_logger = "0.10.0"
