[package]
name = "blake-tree"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
base64 = "0.20.0"
blake3 = "1.3.3"
getrandom = "0.2.8"
hex = "0.4.3"
serde = { version = "1.0.152", features = ["derive"] }
sled = "0.34.7"

[dev-dependencies]
bao = "0.12.1"
